#include <iostream>

using namespace std;

int main() {
    try {
        int numerator, denominator, result;

        cout << "Enter numerator: ";
        cin >> numerator;

        cout << "Enter denominator: ";
        cin >> denominator;

        if (denominator == 0) {
            // Throw an exception if denominator is zero
            throw "Division by zero error";
        }

        result = numerator / denominator;
        cout << "Result of division: " << result << endl;
    } catch (const char* msg) {
        // Catch the exception thrown by the division operation
        cout << "Exception caught: " << msg << endl;
    }

    return 0;
}
